export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU'
export const TOGGLE_MENU = "TOGGLE_MENU"
export const TOGGLE_THEME = 'TOGGLE_THEME'
export const TOGGLE_COMMENT_SECTION = "TOGGLE_COMMENT_SECTION"
export const IS_SERVER = 'IS_SERVER'

export const TOGGLE_AUTH_MODAL = " TOGGLE_AUTH_MODAL"